### PR TITLE
Quarkus gRPC benchmark material

### PR DESCRIPTION
**Pull request by nandorholozsnyak**
Hey.
As we talked about that earlier on Twitter, I had some time to do the Quarkus based gRPC projects (simple and GraalVM based native).
I used Maven, cause it feels more natural for me and with Gradle the protobuf plugin had some issues and it is not really working properly right now.

### CODE REVIEW

**Comment by nandorholozsnyak** [comment]
Hey @brunoborges ,
One of the image building fails, you can see it in the logs, I did not change anything related to that module. Can you check it what is the problem?

**Comment by brunoborges** [comment]
Any chance you can send your logs?

**Comment by nandorholozsnyak** [comment]
Here it is:
https://pipelines.actions.githubusercontent.com/14jFFVidAoJ9YII6MhqoW6S0QJGzMCdWXPejWtNTgbHruHVTuc/_apis/pipelines/1/runs/24/signedlogcontent/3?urlExpires=2020-08-28T07%3A57%3A31.4783872Z&urlSigningMethod=HMACV1&urlSignature=e3X%2ByliuRxKNv8LNpywW3PJBVLOHeV82kQt%2F6Ku%2FRVc%3D

**Comment by nandorholozsnyak** [comment]
It is the same as on the master:
https://github.com/brunoborges/grpc_bench/actions/runs/228111552

**Comment by brunoborges** [comment]
Can you try again with what's in `master`? I committed what was missing.

**Comment by nandorholozsnyak** [comment]
Yes I will.

**Comment by nandorholozsnyak** [comment]
@brunoborges I fixed the builds but it failed again and I find no proper info in the logs. Can you take a look on them?
This is the last build: https://github.com/brunoborges/grpc_bench/pull/1/checks?check_run_id=1049994849

**Comment by nandorholozsnyak** [comment]
Hey @brunoborges , I just updated the Quarkus version and the CI successfully run. Can you take a look on it and merge if it looks fine?

**Pull request merged**
